### ISSUE TITLE
Can’t get menu bar item "Control Center" of menu bar 1 of application process "ControlCenter".

### ISSUE THREAD

**Issue by rgeissen** [kconsiglio/auto-open-screen-mirroring#1]
Whenever I try to run the script I am getting the following error:

System Events got an error: Can’t get menu bar item "Control Center" of menu bar 1 of application process "ControlCenter".

I am on MACOS 13.0

**Comment by kconsiglio** [comment]
Hi, currently this will not work on Ventura (MacOS 13+). Unfortunately, Apple changed some things that breaks the script. Like the name for the "Control Center" item is now in the description of that item not the actual name value. I have a partial fix I'm working on I just need to test before pushing.

**Comment by kconsiglio** [comment]
@rgeissen   I have added some partial support for Ventura. It will open Control Center and click Screen Mirroring but can't click a device yet.

**Comment by kconsiglio** [comment]
Issue should be fixed on Ventura now. I also added support to handle different languages, since that could also cause some breaking issues as the "window" names change between languages.

**Comment by rgeissen** [comment]
Unfortunately still doesn't work. 
osascript open_airplay_menu.scpt "IPADRAG"   opens  Screen Mirroring Dialog Box but doesn't select IPADRAG from the dropdown menue. Any advise?
<img width="294" alt="Screenshot 2022-12-06 at 22 12 46" src="https://user-images.githubusercontent.com/13706657/206024343-fda53e94-5c55-4663-a29f-8e5e5ae1671e.png">

**Comment by kconsiglio** [comment]
HI @rgeissen  i have created a new issue since the original error for this issue thread has been resolved. We can discuss further on [this new issue thread](https://github.com/kconsiglio/auto-open-screen-mirroring/issues/2)
