### ISSUE TITLE
Ventura - Device in dropdown does not get selected

### ISSUE THREAD

**Issue by kconsiglio** [kconsiglio/auto-open-screen-mirroring#2]
Screen Mirroring dropdown gets opened but device does not get selected from the drop down.

**Comment by kconsiglio** [comment]
Unfortunately still doesn't work. 
osascript open_airplay_menu.scpt "IPADRAG"   opens  Screen Mirroring Dialog Box but doesn't select IPADRAG from the dropdown menue. Any advise?
<img width="294" alt="Screenshot 2022-12-06 at 22 12 46" src="https://user-images.githubusercontent.com/13706657/206024343-fda53e94-5c55-4663-a29f-8e5e5ae1671e.png">

_Originally posted by @rgeissen in https://github.com/kconsiglio/auto-open-screen-mirroring/issues/1#issuecomment-1340014253_

**Comment by kconsiglio** [comment]
@rgeissen please uncomment the two lines:
`--	log aScreenMirroringItem` (140 & 143) in the `getScreenMirroringDropDown` function.
Also add one line to the repeat loop in that function.
```
repeat with anItem in screenMirroringDropDown
					try
						log anItem -- add this
```


In the mac script editor go to the messages tab and look at the output when you run it and let me know if the devices are listed. For example this is the output for me on my Ventura VM. I am unable to fully test as the VM doesn't support screen mirroring inside of it so that menu is not populated.
![Screenshot 2022-12-05 at 10 06 51 AM](https://user-images.githubusercontent.com/7415348/206033326-e9cc751f-07ae-44dc-bfb0-3b289901564b.png)

**Comment by rgeissen** [comment]
<img width="577" alt="Screenshot 2022-12-07 at 14 28 46" src="https://user-images.githubusercontent.com/13706657/206191770-42882984-2e7e-4fe7-8f9e-5e41a5e75367.png">
I get the same output then yours

**Comment by zlsds** [comment]
> 

I also found the same problem and log. And I'm sure that my Airplay runs successfully.
I just wondering if there is any method to add device name manually rather than through Airplay.

**Comment by kconsiglio** [comment]
@rgeissen I made some changes but put it on a different [branch here](https://github.com/kconsiglio/auto-open-screen-mirroring/tree/dev) for testing. I added a condition for Ventura and changed `set screenMirroringDropDown to UI elements` to `set screenMirroringDropDown to UI elements of group 1` in the `on getScreenMirroringDropDown` function. Which is how it works for BigSur.

**Comment by rgeissen** [comment]
Now it works perfectly, thank you!

Am Mi., 7. Dez. 2022 um 18:35 Uhr schrieb kconsiglio <
***@***.***>:

**Comment by kconsiglio** [comment]
@rgeissen excellent, glad it's working now! Thank you for testing it out for me.
 I'll merge that change over to the main branch.

**Comment by kconsiglio** [comment]
@zlsds this current issue with the device not being selected on Ventura, is fixed now. 

>  I just wondering if there is any method to add device name manually rather than through Airplay.

I'm sorry, could you please clarify? 
Are you saying you want to cast to a device without it going through that dropdown menu? Or to add a device to that menu that isn't there?

**Comment by zlsds** [comment]
> @zlsds this current issue with the device not being selected on Ventura, is fixed now.
> 
> > I just wondering if there is any method to add device name manually rather than through Airplay.
> 
> I'm sorry, could you please clarify? Are you saying you want to cast to a device without it going through that dropdown menu? Or to add a device to that menu that isn't there?

Emm...It still doesn't work for me. My version is 13.1(22C65) which should be published on next week on M1 Mac.
I tried to log airPlayDevice (see the picture below). (I know little about AppleScript so I don't know what it should be)

<img width="687" alt="image" src="https://user-images.githubusercontent.com/115084436/206334800-f8a76d96-f2e7-4163-b45b-183bfe9f68ca.png">

So I just wondering if I can avoid using it and click my device directly without checking airplay.

**Comment by kconsiglio** [comment]
@zlsds The most current version of the script is not working? It did work for the other person but I'm not sure what version they are on. 

As far as it outputting "no arguments" thats because while running in the script editor `airPlayDevice` will be blank since no argument is passed to it. Does the same thing happen if you run from terminal, like on the readme? `osascript open_airplay_menu.scpt "example Device Name"`
Alternatively if you did want to run it from the script editor you could hard code the device name by changing that line `set airPlayDevice to anItem` to `set airPlayDevice to "your devicename"`. 

The script uses gui actions so it will always have to interact by reading and clicking on the menus and items. I'm unsure if there is a way to cast directly without interacting with that menu.

**Comment by zlsds** [comment]
> As far as it outputting "no arguments" thats because while running in the script editor `airPlayDevice` will be blank since no argument is passed to it. Does the same thing happen if you run from terminal, like on the readme? `osascript open_airplay_menu.scpt "example Device Name"` Alternatively if you did want to run it from the script editor you could hard code the device name by changing that line `set airPlayDevice to anItem` to `set airPlayDevice to "your devicename"`.

I tried to run from terminal but it did dot work with latest version. I'm not sure if there is something wrong with my configuration or operation. 

Anyway, the alternative way did work, both in the terminal and code editor. 

Thanks a lot.
